version: '3.8'

services:
  bitcoin-sv:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bitcoin_data:/data
    ports:
      - "0.0.0.0:8333:8333"      # IPv4 P2P
      - "[::]:8334:8333"         # IPv6 P2P (using different host port)
      - "0.0.0.0:8332:8332"      # IPv4 RPC
      - "[::]:8335:8332"         # IPv6 RPC (using different host port)
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-rpcuser}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD:-rpcpassword}
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN  # Required for IPv6 configuration
    networks:
      bitcoin_net:
        ipv6_address: 2001:db8:1::2

networks:
  bitcoin_net:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1

volumes:
  bitcoin_data:
