version: '3.8'

services:
  bitcoin-sv:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bitcoin_data:/data
      - ./bitcoin.conf:/data/bitcoin.conf:ro
    ports:
      - "0.0.0.0:18666:18666"    # IPv4 P2P (changed)
      - "[::]:18667:18666"       # IPv6 P2P (changed)
      - "0.0.0.0:18665:18665"    # IPv4 RPC (changed)
      - "[::]:18668:18665"       # IPv6 RPC (changed)
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-rpcuser}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD:-rpcpassword}
    command:
      - bitcoind
      - -conf=/data/bitcoin.conf
      - -datadir=/data
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    networks:
      bitcoin_net:
        ipv6_address: 2001:db8:1::2

networks:
  bitcoin_net:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1

volumes:
  bitcoin_data:
